name: "Update site"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone this repository"
        uses: actions/checkout@v1

      - name: "Pull a docker image"
        run: docker pull lacti/jekyll-aws

      - name: "Build and deploy"
        run: |
          docker run \
                -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
                -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                -v ${PWD}:/opt \
              lacti/jekyll-aws \
              /bin/bash -c "cd /opt; /bin/bash /opt/sync.sh"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
